Holger
PollyNET/Pollynet_Processing_Chain pull request #67
Opened 2020-09-01 14:00 UTC by HolgerPollyNet

added the storage of the used lidar constant  in netcdf files for att bsc and quasie results as attribute of the backscatters....

2020-09-01 14:23 UTC, ZPYin commented on lib/polly_general_func_lib/pollyxt_save_quasi_results.m
> +netcdf.putAtt(ncID, varID_quasi_bsc_532, 'Lidar_ratiot_used', config.LR532);
please fix the typo here (`Lidar_ratiot_used` to `Lidar_ratio_used`)

2020-09-01 14:24 UTC, ZPYin commented on lib/polly_general_func_lib/pollyxt_save_quasi_results.m
> +netcdf.putAtt(ncID, varID_quasi_bsc_1064, 'Lidar_ratiot_used', config.LR1064);
Same typo here.

2020-09-01 14:28 UTC, ZPYin requested changes
Please fix the typo marked by the comments and then send PR.

2020-09-02 06:38 UTC, HolgerPollyNet commented on lib/polly_general_func_lib/pollyxt_save_quasi_results.m
> +netcdf.putAtt(ncID, varID_quasi_bsc_532, 'Lidar_ratiot_used', config.LR532);
I fixed the typos, thanks for the good reviewing

2020-09-02 06:39 UTC, merged